### ISSUE TITLE
About i7-8700K_lut.yaml

### ISSUE THREAD

**Issue by chakkritte** [mikelzc1990/nsganetv2#2]
Hi @mikelzc1990,

Thank you for sharing your great work.

Look like that i7-8700K_lut.yaml file isn't including this repo.

Could you provide this file?

Thanks.

**Comment by mikelzc1990** [comment]
Just did, it's [here](https://github.com/mikelzc1990/nsganetv2/blob/master/data/i7-8700K_lut.yaml).

**Comment by chakkritte** [comment]
Thanks 😊
